// <auto-generated>
// Generated by Astora Editor. Do not modify manually.
// Regenerate by saving the scene in the editor.
// </auto-generated>

using Astora.Core.Nodes;
using Astora.Core.Scene;
using Microsoft.Xna.Framework;

namespace Astora.SandBox.Scenes;

public partial class SampleScene : IScene
{
    public static string ScenePath => "Scenes/SampleScene";

    public static Node Build()
    {
        var root = SceneBuilder.Create<Node>("SampleScene")
            .Add<Camera2D>("MainCamera")
            .Add<CPUParticles2D>("ParticleEffects", n =>
            {
                n.Amount = 50;
                n.Lifetime = 2f;
                n.Gravity = new Vector2(0f, 0f);
                n.Direction = new Vector2(1f, -1f);
                n.AngularVelocity = 5f;
                n.ColorStart = new Color(255, 200, 100, 255);
                n.ColorEnd = new Color(255, 50, 50, 0);
                n.ScaleStart = 0.5f;
                n.ScaleEnd = 0.1f;
            })
            .Add<Sprite>("SampleSprite", n =>
            {
                n.Origin = new Vector2(70f, 70f);
                n.Modulate = new Color(255, 163, 163, 255);
                n.Offset = new Vector2(-270f, 0f);
                n.TexturePath = "Test.png";
                n.Position = new Vector2(-226f, -378f);
                n.Rotation = 1.012291f;
            })
            .Build();

        OnBuild(root);
        return root;
    }

    static partial void OnBuild(Node root);
}
