using Astora.Core.Nodes;
using Astora.Core.Utils;
using FluentAssertions;
using Microsoft.Xna.Framework;

namespace Astora.Core.Tests.Scene;

public class SceneCodeEmitterTests
{
    [Fact]
    public void Emit_SimpleScene_GeneratesSceneBuilderCode()
    {
        var root = new Node("SampleScene");

        var camera = new Camera2D("MainCamera");
        root.AddChild(camera);

        var sprite = new Sprite();
        sprite.Name = "SampleSprite";
        sprite.Position = new Vector2(314, 360);
        sprite.Rotation = 1.012291f;
        sprite.TexturePath = "Test.png";
        sprite.Modulate = new Color(255, 163, 163, 255);
        sprite.Offset = new Vector2(-270, 0);
        root.AddChild(sprite);

        var emitter = new SceneCodeEmitter();
        var code = emitter.Emit(root, "MyGame.Scenes", "SampleScene", "Scenes/SampleScene");

        // Structure checks
        code.Should().Contain("// <auto-generated>");
        code.Should().Contain("namespace MyGame.Scenes;");
        code.Should().Contain("public partial class SampleScene : IScene");
        code.Should().Contain("public static string ScenePath => \"Scenes/SampleScene\";");
        code.Should().Contain("public static Node Build()");
        code.Should().Contain("static partial void OnBuild(Node root);");

        // SceneBuilder API usage
        code.Should().Contain("SceneBuilder.Create<Node>(\"SampleScene\")");
        code.Should().Contain(".Add<Camera2D>(\"MainCamera\")");
        code.Should().Contain(".Add<Sprite>(\"SampleSprite\", n =>");
        code.Should().Contain("n.Position = new Vector2(314f, 360f);");
        code.Should().Contain("n.TexturePath = \"Test.png\";");
        code.Should().Contain(".Build();");
        code.Should().Contain("OnBuild(root);");
        code.Should().Contain("return root;");
    }

    [Fact]
    public void Emit_DefaultProperties_AreOmitted()
    {
        var root = new Node("Root");
        var child = new Node2D("Child");
        root.AddChild(child);

        var emitter = new SceneCodeEmitter();
        var code = emitter.Emit(root, "Test", "TestScene", "Scenes/Test");

        // No property configuration needed — should use simple .Add
        code.Should().Contain(".Add<Node2D>(\"Child\")");
        code.Should().NotContain("Position =");
        code.Should().NotContain("Rotation =");
        code.Should().NotContain("Scale =");
        code.Should().NotContain("n =>");
    }

    [Fact]
    public void Emit_NestedChildren_UsesAddChild()
    {
        var root = new Node("Root");
        var parent = new Node2D("Parent");
        var child = new Node2D("Child");
        parent.AddChild(child);
        root.AddChild(parent);

        var emitter = new SceneCodeEmitter();
        var code = emitter.Emit(root, "Test", "TestScene", "Scenes/Test");

        // Parent has a child → AddChild with builder callback
        code.Should().Contain(".AddChild<Node2D>(\"Parent\", b => b");
        // Inside the callback, child is added
        code.Should().Contain(".Add<Node2D>(\"Child\")");
        code.Should().Contain(")"); // closing of AddChild
    }

    [Fact]
    public void Emit_DeepNesting_ProducesCorrectIndentation()
    {
        // Build: Root > Container > Panel > Leaf
        var root = new Node("Root");
        var container = new Node2D("Container");
        var panel = new Node2D("Panel");
        var leaf = new Node2D("Leaf");
        panel.AddChild(leaf);
        container.AddChild(panel);
        root.AddChild(container);
        root.AddChild(new Camera2D("Cam"));

        var emitter = new SceneCodeEmitter();
        var code = emitter.Emit(root, "Test", "TestScene", "Scenes/Test");

        // Nested AddChild calls
        code.Should().Contain("            .AddChild<Node2D>(\"Container\", b => b");
        code.Should().Contain("                .AddChild<Node2D>(\"Panel\", b => b");
        code.Should().Contain("                    .Add<Node2D>(\"Leaf\")");
        // Closing parens at correct indentation
        code.Should().Contain("                )");
        code.Should().Contain("            )");
        // Cam is a leaf at root level
        code.Should().Contain("            .Add<Camera2D>(\"Cam\")");
        code.Should().Contain("            .Build();");
    }

    [Fact]
    public void Emit_BranchWithProperties_UsesConfigureInsideAddChild()
    {
        // A node with both children and non-default properties
        var root = new Node("Root");
        var branch = new Node2D("Branch");
        branch.Position = new Vector2(100f, 200f);
        var leaf = new Node2D("Leaf");
        branch.AddChild(leaf);
        root.AddChild(branch);

        var emitter = new SceneCodeEmitter();
        var code = emitter.Emit(root, "Test", "TestScene", "Scenes/Test");

        // Should use AddChild with Configure inside builder callback
        code.Should().Contain(".AddChild<Node2D>(\"Branch\", b => b");
        code.Should().Contain(".Configure<Node2D>(n =>");
        code.Should().Contain("n.Position = new Vector2(100f, 200f);");
        code.Should().Contain(".Add<Node2D>(\"Leaf\")");
    }

    [Fact]
    public void Emit_LeafWithProperties_UsesAddWithConfigure()
    {
        var root = new Node("Root");
        var child = new Node2D("Child");
        child.Position = new Vector2(42, 84);
        root.AddChild(child);

        var emitter = new SceneCodeEmitter();
        var code = emitter.Emit(root, "Test", "TestScene", "Scenes/Test");

        // Leaf with properties → .Add<T>("Name", n => { ... })
        code.Should().Contain(".Add<Node2D>(\"Child\", n =>");
        code.Should().Contain("n.Position = new Vector2(42f, 84f);");
    }
}
